### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by solson** [brixen/redcard#3]
This code verifies exactly what it says:

``` ruby
RedCard.verify "1.9", :rubinius => "2.0"
```

But when I run it on MRI 1.9, the error message is misleading:

```
/home/scott/.rvm/gems/ruby-1.9.3-p194/gems/redcard-1.1.0/lib/redcard.rb:17:in `verify': ruby version 1.9.3 is not supported (RedCard::InvalidRubyError)
```

It should say that Rubinius is required.

**Comment by bf4** [comment]
Yeah, instead it is says, paraphrasing "You are currently running cruby, there is no 1.9 version"  Perhaps it should say "You are checking against rubinius engine version 2.0 , there is no ruby version 1.9"

The current code's logic is a little confusing
1. get your vm's RUBY_ENGINE. If it doesn't have one, it's 'ruby' (mri)
2. the engine version (i.e. the version for this vm) can return a numerical string for jruby,ruby,maglev,rbx,topaz
3. check the arguments 
   1. false if an engine is specified (:jruby) and it doesn't match the current engine, e.g. 'jruby' == 'jruby'
   2. false if an  version is specified ('1.9.3') and doesn't match the current engine '1.9.3' == '1.9.3'
   3. true if no engine versions specified
   4. true/false whether the engine version specified matches the current engine and version e.g. :jruby => '1.9.3'
   5. false

So, the check above fails at step 4 where the current engine is not rubiniuis with version 1.9.3 but returns an error with the current ruby engine https://github.com/brixen/redcard/blob/master/lib/redcard.rb#L80

In my case, I get the following strange behavior running on osx rvm cruby 1.9.3-p448 redcard v 1.1.0

``` ruby
RedCard.check => true
RedCard.check(:ruby) => true
RedCard.check('1.8') => true
RedCard.check('1.9') => true
RedCard.check('2.0') => false
RedCard.check(2.0) => true
RedCard.check('brixen') => true
RedCard.check(:jruby) => false
RedCard.check(:jruuuby) => false
RedCard.check(:ruby => 'brixen') => true
```

Digging in

``` ruby
r = RedCard.new('1.8'); p [r.check, r.message, r.error] => [true, nil, nil]
RedCard::Version.new(RUBY_VERSION, '1.8').valid? => true # shouldn't that be RedCard.engine_version ?
# where 
@version => 100100900300000
@minimum       => 100100800000000
@maximum      => nil
@version >=  @minimum => true
@maxmimum.nil? => true # which is what it returns
# so, let's dig in
RedCard::Version.new(RUBY_VERSION, ('1.8'..'1.9'))
@version        => 100100900300000
@minimum     =>  100100800000000
@maximum    => 100100900000000
@version >=  @minimum => true
@version <=  @maximum => false # i.e. 1.9.3 is > 1.9

so
RedCard.check('1.9'..'2.0') => true
RedCard.check('1.9'..'1.9.1') => false
RedCard.check('1.8'...'1.9') => false
```

That's not the behavior I would have expected.
